[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "astacus"
authors = [
  { name="Aiven", email="opensource@aiven.io" },
]
description = "Astacus, cluster (database) backup tool"
readme = "README.md"
requires-python = ">=3.11"
classifiers=[
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: System Administrators",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.11",
    "Topic :: Database :: Database Engines/Servers",
    "Topic :: Software Development :: Libraries",
]
license = { text = "Apache License 2.0" }
dynamic = ["version"]
dependencies = [
    "fastapi",
    "httpx",
    "msgspec",
    "kazoo",
    "protobuf < 3.21",
    "pydantic < 2",
    "pyyaml",
    "rohmu >= 2.2.0",
    "sentry-sdk",
    "tabulate",
    "typing-extensions >= 4.7.1; python_version < '3.12'",
    "uvicorn",
    "wcmatch",
]

[project.optional-dependencies]
dev = [
    # Needed by pre-commit to lint and test the project
    "pre-commit>=3.7.0",
    "anyio==3.5.0",
    "pylint==2.17.4",
    "pytest-asyncio==0.21.1",
    "pytest-cov==3.0.0",
    "pytest-mock==3.10.0",
    "pytest-order==1.0.0",
    "pytest-timeout==1.4.2",
    "pytest-watch==4.2.0",
    "pytest==7.2.2",
    "mypy==1.9.0",
    # Types for things that don't seem to have them
    "types-botocore>=1.0.2",
    "types-PyYAML>=6.0.12.2",
    "types-requests>=2.28.11.5",
    "types-tabulate>=0.9.0.0",
    "types-ujson>=5.9.0.0",
    "types-urllib3>=1.26.25.4",
    # F38
    "coverage==7.0.5",
    "freezegun>=1.2",
    "respx==0.20.1",
]

[project.urls]
"Homepage" = "https://github.com/Aiven-Open/astacus"
"Bug Tracker" = "https://github.com/Aiven-Open/astacus/issues"

[project.scripts]
astacus = "astacus.main:main"


[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.vcs]
version-file = "astacus/version.py"


[tool.black]
line-length = 125

[tool.isort]
no_sections = true
force_alphabetical_sort = true
combine_as_imports = true
profile = "black"
skip_gitignore = true
line_length = 125

[tool.coverage.run]
# Gather statistics per invocation
parallel = true

# We're only interested about Astacus core, not rohmu/..
#
# (tests is listed here mostly so that we can detect unused utility functions in them)
source = [
     "astacus",
     "tests"
]
