name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: make build-dep-ubuntu

      - name: Set up Python 3.11 with caching
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run all pre-commit hooks
        run: make lint

  copyright:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master

        - name: Enforce copyright headers
          run: make copyright
