name: Lint

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make build-dep-ubuntu

      - name: Set up Python 3.11 with caching
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install testing requirements
        run: pip install -r requirements.testing.txt

      - name: generate version
        run: make generate_version_from_git

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run all pre-commit hooks
        run: make lint

  copyright:
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v3

        - name: Enforce copyright headers
          run: make copyright
