name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: make build-dep-ubuntu

      - name: Install requirements
        run: python3 -m pip install -r requirements.txt

      - name: Run all pre-commit hooks
        run: make lint

  copyright:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master

        - name: Enforce copyright headers
          run: make copyright
