name: Test Suite (Minimal)

on: pull_request

# Note: This test runs only on one Python version the minimal pip install

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9"]
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make build-dep-ubuntu test-dep-ubuntu

      - name: Set up Python ${{ matrix.python-version }} with caching
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Execute unit-tests
        run: make unittest
