name: Test Suite (Maximal)

on: pull_request

jobs:
  unit-test:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10']
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: make build-dep-ubuntu test-dep-ubuntu

    - name: Set up Python ${{ matrix.python-version }} with caching
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install requirements
      run: pip install -e '.[cassandra]'

    - name: Install testing requirements (not included by default in normal install)
      run: pip install -r requirements.testing.txt

    - name: Execute unit-tests
      run: make unittest
