name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-test:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make build-dep-ubuntu test-dep-ubuntu

    - name: Set up Python ${{ matrix.python-version }} with caching
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install requirements
      run: pip install -e '.[cassandra]'

    - name: Install testing requirements (not included by default in normal install)
      run: pip install -r requirements.testing.txt

    - name: Execute unit-tests
      run: make unittest

    - id: upload-codecov
      # Third-party action pinned to v2.1.0
      uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b
      with:
        verbose: true
